services:
  - type: web
    name: dulichviet
    env: python
    buildCommand: ""
    startCommand: gunicorn TourNhanh.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tourapp.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'False'
